FROM node:14.15.1-slim
# Create app directory
WORKDIR /usr/src

COPY proto ./proto

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY gateway ./
RUN yarn

# If you are building your code for production
# RUN yarn ci --only=production

EXPOSE 4000

CMD [ "yarn", "start" ]